# Generated by Django 3.1.2 on 2020-10-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('course_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('course_name', models.CharField(max_length=200)),
                ('course_language', models.CharField(choices=[('PL', 'Small'), ('EN', 'Medium')], max_length=2)),
                ('course_location', models.CharField(choices=[('IL', 'Inland waters'), ('OS', 'Open sea waters')], max_length=2)),
                ('course_start_date', models.DateTimeField()),
                ('course_end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=40)),
                ('position_description', models.CharField(max_length=200)),
                ('position_salary_range', models.CharField(max_length=40)),
                ('is_trainer', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Yacht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yacht_id', models.IntegerField()),
                ('yacht_name', models.CharField(max_length=40)),
                ('yacht_model', models.CharField(max_length=40)),
                ('yacht_production_date', models.DateTimeField()),
                ('yacht_our_registration_date', models.DateTimeField()),
                ('yacht_length', models.IntegerField()),
                ('yacht_max_crew', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=40)),
                ('student_surname', models.CharField(max_length=40)),
                ('student_PESEL', models.IntegerField()),
                ('student_phone_number', models.CharField(max_length=20)),
                ('student_address', models.CharField(max_length=200)),
                ('student_birth_date', models.DateTimeField()),
                ('student_amount_due', models.DecimalField(decimal_places=2, max_digits=8)),
                ('course_attended', models.ManyToManyField(to='school.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=40)),
                ('employee_surname', models.CharField(max_length=40)),
                ('employee_start_date', models.DateTimeField()),
                ('employee_PESEL', models.IntegerField()),
                ('employee_phone_number', models.CharField(max_length=20)),
                ('employee_address', models.CharField(max_length=100)),
                ('position_salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('employee_position', models.ManyToManyField(to='school.Position')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_instructor',
            field=models.ManyToManyField(to='school.Employee'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_yachts_assigned',
            field=models.ManyToManyField(to='school.Yacht'),
        ),
    ]
