# Generated by Django 3.1.2 on 2020-10-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_language',
            field=models.CharField(choices=[('PL', 'Polski'), ('EN', 'English')], max_length=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='yacht_our_registration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='yacht_production_date',
            field=models.DateField(),
        ),
    ]
